<?php

namespace SysBackenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuCategoriesRepository extends EntityRepository
{
    function find_categories_childrenQueryBuilder(){
        $QueryBuilder = $this->createQueryBuilder('n')->where('n.parent <> 0')->orderBy('n.name');
        return $QueryBuilder;
    }
}
